### ISSUE TITLE
如何用这个输入繁体呢?

### ISSUE THREAD

**Issue by Jiang10086** [placeless/squirrel_config#3]
繁体字的小鹤双拼输入

**Comment by placeless** [comment]
抱歉，我自己用不到，所以繁体需要自行微调。

**Comment by iDvel** [comment]
我是参考这里弄的 https://github.com/rime/home/issues/388 
我的示例：
```
patch:
  switches:
    - name: traditionalization
      reset: 0
      states: [简, 繁]
  
  key_binder/bindings/+:
    - {when: always, accept: Control+Shift+4, toggle: traditionalization}

  engine/filters:
    - simplifier@traditionalize
    - uniquifier
  
  traditionalize:
    opencc_config: s2t.json
    option_name: traditionalization
    tips: all # 简入繁出，注销掉可直接出繁
```

这个快捷键我想改成 Control+Shift+f 的，不知道为啥改了没用。。。
