### ISSUE TITLE
请问如何切换到常规的数字按键选词啊？

### ISSUE THREAD

**Issue by MrWrh** [placeless/squirrel_config#6]
用的时候发现，这个配置方案启用了alternative_select_keys的功能，请问如何切换到常规的数字按键选词啊？多谢！

**Comment by placeless** [comment]
需要做几个调整，比如把数字从输入码中拿掉，注释掉个性候选按键等

```yaml
speller:
  alphabet: 'zyxwvutsrqponmlkjihgfedcba0987654321:,.!()/-=_+'
  initials: 'zyxwvutsrqponmlkjihgfedcba0987654321'

menu:
  page_size: 2
  alternative_select_keys: "';"
```
