### ISSUE TITLE
请教如何使用 shift 进行中英切换？

### ISSUE THREAD

**Issue by llj098** [placeless/squirrel_config#7]
如题，貌似 shift 键不能中英切换。在 linux 上习惯了 shift 切换了，请问如何设置 shift 中英切换？

谢谢！

**Comment by placeless** [comment]
你可以尝试在 `default.custom.yaml` 中增加配置

```yaml
ascii_composer/switch_key:
  Caps_Lock: noop
  Control_L: noop
  Control_R: noop
  Shift_L: commit_code
  Shift_R: noop

# inline_ascii 在輸入法的臨時西文編輯區內輸入字母、數字、符號、空格等，回車上屏後自動復位到中文
# commit_text 已輸入的候選文字上屏並切換至西文輸入模式
# commit_code 已輸入的編碼字符上屏並切換至西文輸入模式
# 設爲 noop，屏蔽該切換鍵
```
