### ISSUE TITLE
下载了2021的配置，但是我不会配置，有几个想要的功能无法成功，需要向您请教：

### ISSUE THREAD

**Issue by haiwz** [placeless/squirrel_config#8]
我在default.custom.yaml里设置如下：
```
patch:
  schema_list:
    - schema: placeless_flypy
  switcher/hotkeys:
    - "Control+grave"
  switches:
    - name: traditionalization
      reset: 0
      states: [简, 繁]
  ascii_composer/switch_key:
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Shift_L: noop
    Shift_R: commit_code
```

问题1：Control+`菜单里没有切换简繁模式。
问题2：右边的shift无法切换英文输入状态。
问题3：为什么0-9单个数字输入的时候为什么无法直接上屏？如果要单独输入的时候直接上屏是不是就没办法在句子里输入数字了？
问题4:  怎么快速切换皮肤？

谢谢️！
